# FROM zeuik/ruby-3.0.3:latest
FROM zeuik/ruby-3.0.5-slim:latest
# Define where our application will live inside the image
ENV RAILS_ROOT /var/www/rails
# Set our working directory inside the image
WORKDIR $RAILS_ROOT

RUN curl -L https://github.com/Paktor/Goodnight-aws-env/releases/download/v0.7/aws-env-linux-amd64 --output /bin/aws-env && \
  chmod +x /bin/aws-env
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN echo bundle --version
RUN bundle install